from company import *


year = Class(2)
first_topic = Topic('Числа   от   1   до   100. Нумерация.')
lvl_1 = Level(1, info='Привет! Немного повторения на числа от 1 до 20.')
lvl_1.add(Task(text='Назови число, которы встречаются при счете между 17 и 19', answer='18'))
lvl_1.add(Task(text='А теперь число между 15 и 17', answer='16'))
lvl_1.add(Task(text='Что же находится между 11 и 9?', answer='10'))
lvl_1.add(Task(text='А чему равна сумма чисел между 2 и 5?', answer='7'))

lvl_2 = Level(1, info='Теперь немного примеров!')
lvl_2.add(Task(text='Увеличь на 3 число 7, напиши ответ.', answer='10'))
lvl_2.add(Task(text='А теперь увеличь на 2 число 10', answer='12'))
lvl_2.add(Task(text='Теперь уменьши на 2 число 12', answer='18'))
lvl_2.add(Task(text='Уменьши 9 на 3', answer='6'))

lvl_3 = Level(1, info='Порешаем задачки!')
lvl_3.add(Task(text='В одной коробке 10 карандашей, а в другой 6, сколько всего?', answer='16'))
lvl_3.add(Task(text='У Васи было 5 тетрадей в клетку и столько же в линейку. Сколько у него всего тетрадей?', answer='10'))
lvl_3.add(Task(text='А сколько у него останется, если он отдаст 2 тетради в линейку другу?', answer='8'))
lvl_3.add(Task(text='А сколько у Васи осталось тетрадей в линейку?', answer='3'))

lvl_4 = Level(1, info='Больше задач!')
lvl_4.add(Task(text='В первом ряду кинотеатра 8 мест, а во втором на 2 места больше. Сколько мест во втором ряду?', answer='10'))
lvl_4.add(Task(text='А сколько всего мест в кинотеатре?', answer='18'))
lvl_4.add(Task(text='Длина первого звена ломаной 1 дм, а второго 3 см. Какая длина всей этой ломанной в сантиметрах?', answer='13'))
lvl_4.add(Task(text='Дима старше Оли на 6 лет, а Даша моложе димы на 4 года. Кто старше: Оля или Даша?', answer='Даша'))

lvl_5 = Level(1, info='Будем учиться вести счёт десятками!')
lvl_5.add(Task(text='Сколько будет 3 дес. + 1 дес.? Ответ дай в десятках.', answer='2'))
lvl_5.add(Task(text='Сколько будет 4 дес. + 5 дес.? Теперь ответ уже числом.', answer='90'))
lvl_5.add(Task(text='А сколько числом 9 дес. - 5 дес.?', answer='40'))
lvl_5.add(Task(text='Сколько будет 5 дес. - 2 дес. числом?', answer='30'))

lvl_5 = Level(1, info='Теперь задачи на десятки!')
lvl_5.add(Task(text='У Васи было 3 десятка марок. Он подарил другу 10 марок. Сколько у Васи осталось марок?', answer='20'))
lvl_5.add(Task(text='Папе 40 лет, а маме 30. На сколько лет папа старше мамы?', answer='10'))
lvl_5.add(Task(text='У Вари было 30 пуговиц, она пришила двадцать. Сколько у нее осталось пуговиц?', answer='10'))

lvl_6 = Level(1, info='Добавим к десяткам единицы!')
lvl_6.add(Task(text='Назови число, в котором 1 дес. 9 ед.', answer='19'))
lvl_6.add(Task(text='А теперь число, в котором 9 дес. 1 ед.', answer='91'))
lvl_6.add(Task(text='Назови число, в котором 10 дес.', answer='100'))
lvl_6.add(Task(text='Осталось число, в котором 2 дес. 3 ед.', answer='23'))

lvl_7 = Level(1, info='Какое число пропущено в ряду?')
lvl_7.add(Task(text='39, 40, ?, 42, 43', answer='41'))
lvl_7.add(Task(text='89, ?, 91, 92, 93', answer='90'))
lvl_7.add(Task(text='76, ?, 74, 73, 72', answer='75'))

lvl_8 = Level(1, info='Ребусы!')
lvl_8.add(Task(text='** + 1 = ***. Что обозначено **?', answer='99'))
lvl_8.add(Task(text='39 + ? = 40.', answer='1'))
lvl_8.add(Task(text='? - 1 = 79', answer='80'))
lvl_8.add(Task(text='? + 1 = 90', answer='89'))

lvl_9 = Level(1, info='Задачки.')
lvl_9.add(Task(text='Миша выиграл 6 партий, а Ваня на 2 партии больше. Сколько раз сыграл Миша?', answer='14'))
lvl_9.add(Task(text='У Коли 10 книг дома, он отнёс 2 в школу. Сколько у него осталось книг дома?', answer='8'))
lvl_9.add(Task(text='На столе лежат: морковка, помидор, огурец и свекла.'
                    ' Сколькими способами можно составить набор и двух овощей?', answer='12'))

lvl_10 = Level(1, info='Закрепим материалы!', style='test', time=60, topic='Числа   от   1   до   100. Нумерация.')
lvl_10.add(Task(text='Назови число, в котором 3 дес. 9 ед.', answer='39'))
lvl_10.add(Task(text='На столе лежат: помидор, кабачок и картошка. Сколькими '
                     'способами можно составить набор и двух овощей?', answer='6'))
lvl_10.add(Task(text='? - 6 = 74', answer='80'))
lvl_10.add(Task(text='86, 85, ?, 83, 82', answer='84'))
lvl_10.add(Task(text='Петя выиграл 2 партии, а Ваня на 6 партии больше. Сколько раз сыграл Ваня?', answer='10'))
lvl_10.add(Task(text='В первом ряду кинотеатра 10 мест, а во втором на 4 места больше. Сколько всего мест?', answer='24'))
first_topic.add_level(lvl_1)
first_topic.add_level(lvl_2)
first_topic.add_level(lvl_3)
first_topic.add_level(lvl_4)
first_topic.add_level(lvl_5)
first_topic.add_level(lvl_6)
first_topic.add_level(lvl_7)
first_topic.add_level(lvl_8)
first_topic.add_level(lvl_9)
first_topic.add_level(lvl_10)
year.add_level(first_topic)

second_topic = Topic('Числа   от   1   до   100. Сложение и вычитание')
lvl_1 = Level(1, info='Привет! Рассмотрим отрезки.')
lvl_1.add(Task(text='Сколько отрезков на этом чертеже?', answer='3', image='pic/100.jpg'))
lvl_1.add(Task(text='Чему равна длина самого большого отрезка?', answer='8', image='pic/100.jpg'))
lvl_1.add(Task(text='Начерти отрезок 10 см. Поставь точку так,'
                    ' чтобы получился отрезок 4 см. Какова длина второго отрезка?', answer='6', image='pic/100.jpg'))

lvl_2 = Level(1, info='Немного примеров!')
lvl_2.add(Task(text='12 - 8 + 9', answer='13'))
lvl_2.add(Task(text='17 - 8 + 6', answer='15'))
lvl_2.add(Task(text='48 - 40 - 8', answer='0'))
lvl_2.add(Task(text='0 + 88 - 8', answer='80'))

lvl_3 = Level(1, info='Ещё примеры!')
lvl_3.add(Task(text='60 - 50 + 3', answer='13'))
lvl_3.add(Task(text='11 - 8 + 7', answer='10'))
lvl_3.add(Task(text='100 - 60 + 3', answer='43'))
lvl_3.add(Task(text='30 + 20 + 3', answer='53'))

lvl_4 = Level(1, info='Составь задачу по картинке и реши ее!')
lvl_4.add(Task(answer='9', image='101.jpg'))
lvl_4.add(Task(answer='4', image='102.jpg'))
lvl_4.add(Task(text='Задача первая', answer='5', image='103.jpg'))
lvl_4.add(Task(text='А теперь вторая', answer='11', image='103.jpg'))

lvl_5 = Level(1, info='Сравнение!')
lvl_5.add(Task(text='38 мм ? 4 см', answer='<', choice=['>', '<', '=']))
lvl_5.add(Task(text='23 мм ? 2 см', answer='>', choice=['>', '<', '=']))
lvl_5.add(Task(text='1 см 8 мм ? 20 мм', answer='<', choice=['>', '<', '=']))
lvl_5.add(Task(text='1 дм 1 см ? 100 мм', answer='>', choice=['>', '<', '=']))

lvl_6 = Level(1, info='А теперь задачи на часы и минуты.')
lvl_6.add(Task(text='Первая игра заняла 50 минут, а вторая шла на 10 дольше. Сколько целых часов всего играли?', answer='1'))
lvl_6.add(Task(text='Мальчик делал домашнее задание час, а потом играл в игры 30 минут. Сколько всего минут прошло? ', answer='90'))


lvl_7 = Level(1, info='Поработаем с ломаными, готовь линейку, карандаш и циркуль!')
lvl_7.add(Task(answer='=', choice=['>', '<', '='], image='104.jpg'))
lvl_7.add(Task(text='Какая длина этой ломаной в сантиметрах?', answer='11', image='105.jpg'))
lvl_7.add(Task(text='А теперь найди её длину', answer='7', image='106.jpg'))

lvl_8 = Level(1, info='Ребусы!')
lvl_8.add(Task(text='? + 8 = 15', answer='7'))
lvl_8.add(Task(text='14 ... = 18', answer='+ 7', choice=['+ 7', '+ 6', '- 4']))
lvl_8.add(Task(text='19 ... = 10', answer='- 9'))
lvl_8.add(Task(text='0 ,,, = 10', answer='+ 10'))

lvl_9 = Level(1, info='Примеры!')
lvl_9.add(Task(text='40 - 21 + 11', answer='30'))
lvl_9.add(Task(text='11 + 10 - 4', answer='17'))
lvl_9.add(Task(text='80 - 40 + 11', answer='51'))
lvl_9.add(Task(text='23 - 13 + 0', answer='10'))

lvl_10 = Level(1, info='Закрепим пройденное!', style='test', time=60, topic='Числа   от   1   до   100. Сложение и вычитание.')
lvl_10.add(Task(text='80 + 12', answer='92'))
lvl_10.add(Task(text='Первая игра заняла 1 час, а вторая шла на 10 минут. Сколько минут шли ргы вместе?', answer='70'))
lvl_10.add(Task(text='? + 11 = 20', answer='9'))
lvl_10.add(Task(text='80 - ? = 30', answer='9'))
lvl_10.add(Task(text='1 дм 12 см ? 13 см 100 мм', answer='<', choice=['>', '<', '=']))
lvl_10.add(Task(text='64 - 62 + 4', answer='6'))
second_topic.add_level(lvl_1)
second_topic.add_level(lvl_2)
second_topic.add_level(lvl_3)
second_topic.add_level(lvl_4)
second_topic.add_level(lvl_5)
second_topic.add_level(lvl_6)
second_topic.add_level(lvl_7)
second_topic.add_level(lvl_8)
second_topic.add_level(lvl_9)
second_topic.add_level(lvl_10)
year.add_level(second_topic)
